

services:
  backend:
    image: shubhamkhatik/test:backendv1
    ports:
      - "5000:5000"

  frontend:
    image: shubhamkhatik/test:frontendv1
    ports:
      - "5173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
